name: Pull Request Tests

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  GenerateNotes:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: semver-patch
