name: Pull Request Notes Action

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  GenerateNotes:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: semver-patch
        if: ${{ !contains(steps.pr-labels.outputs.labels , 'semver-') }}
      - name: Update PR_<Number>.yaml
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: "unreleased_doc/PR_$NUMBER.yaml"
          changes: |
            {
              "title": "${{ github.event.pull_request.title }}",
              "pullRequest": ${{ github.event.pull_request.number }},
              "author": "${{ github.event.pull_request.user.login }}",
              "labels": ${{ steps.pr-labels.outputs.labels }},
              "semver": "ToDo"
            }
          commitChange: true
