name: Pull Request Notes Action

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  GenerateNotes:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8
      - name: Check for existing semver label
        if: contains(steps.pr-labels.outputs.labels, 'semver-')
        run: echo "Semver label found"
